sudo: required

services:
  - docker

before_install:
  - docker build -t lemjak/travisfrontend -f ./Docker_Lab_1-6/frontend/Dockerfile.dev ./Docker_Lab_1-6/frontend

script:
  - docker run -e CI=true lemjak/travisfrontend yarn test
